### ISSUE TITLE
Preprocessed Data

### ISSUE THREAD

**Issue by chetan1836** [googlebaba/WWW2020-O2MAC#2]
I'm having hard time downloading the Preprocessed-Data through Baidu. Can you upload to google drive or something.

**Comment by chetan1836** [comment]
Sorry I didn't read Readme file properly.

**Comment by googlebaba** [comment]
I have uploaded them at: https://drive.google.com/file/d/1uF64x8IgiqQMUeepRDOmY6KSkWKtfGjz/view?usp=sharing
