### ISSUE TITLE
IMDB dataset labels have a little mistake

### ISSUE THREAD

**Issue by Noval11** [googlebaba/WWW2020-O2MAC#6]
Hi, thanks for your work, It helps me a lot. 
In imdb dataset, I find the matrix corresponding to some labels is [0,0,0], this makes it not in any class.  I guess the script for data processing hava bug.  Can you upload the script, or re upload the correct data？

**Comment by googlebaba** [comment]
Thanks for your interest and finding. As I also use others' processed data, I can not correct the preprocessing process. If the number of error labeled nodes is not big, I suggest you delete them.

**Comment by Noval11** [comment]
Well, I'm going to replace it with another dataset. 
By the way, there are 1493 nodes whose labels are wrong!
